version: '3'
services:
  db:
    container_name: builders-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: builders
      MYSQL_ROOT_PASSWORD: builders123
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3386:3306"
    restart: always
