version: '3'
services:
  db:
    container_name: builders-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: builders
      MYSQL_ROOT_PASSWORD: builders123
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3386:3306"
    restart: always
    networks:
      - rede-interna
      
  app:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean test spring-boot:run
    ports:
    - "8080:8080"
    depends_on:
    - db
    networks:
      - rede-interna
      
networks:
  rede-interna:
    driver: bridge